// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace btlnhom32.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20221129074318_Thuonghieu")]
    partial class Thuonghieu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("btl_nhom32.Models.Chucvucv", b =>
                {
                    b.Property<string>("Idcv")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motacn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tencv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Idcv");

                    b.ToTable("Chucvucv");
                });

            modelBuilder.Entity("btl_nhom32.Models.Nhacungcap", b =>
                {
                    b.Property<string>("Mancc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachincc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emailncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sdtncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngayncc")
                        .HasColumnType("TEXT");

                    b.HasKey("Mancc");

                    b.ToTable("Nhacungcap");
                });

            modelBuilder.Entity("btl_nhom32.Models.Nhanvien", b =>
                {
                    b.Property<string>("Manv")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachinv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emailnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gioitinhnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sdtnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tencv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tennv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngaylamnv")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngaynv")
                        .HasColumnType("TEXT");

                    b.HasKey("Manv");

                    b.HasIndex("Tencv");

                    b.ToTable("Nhanvien");
                });

            modelBuilder.Entity("btl_nhom32.Models.Thuonghieu", b =>
                {
                    b.Property<string>("Idth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Idth");

                    b.ToTable("Thuonghieu");
                });

            modelBuilder.Entity("btl_nhom32.Models.Nhanvien", b =>
                {
                    b.HasOne("btl_nhom32.Models.Chucvucv", "Chucvucv")
                        .WithMany()
                        .HasForeignKey("Tencv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chucvucv");
                });
#pragma warning restore 612, 618
        }
    }
}
