// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace btlnhom32.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20221129071855_Chucvucv")]
    partial class Chucvucv
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("btl_nhom32.Models.Chucvucv", b =>
                {
                    b.Property<string>("Idcv")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motacn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tencv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Idcv");

                    b.ToTable("Chucvucv");
                });

            modelBuilder.Entity("btl_nhom32.Models.Nhacungcap", b =>
                {
                    b.Property<string>("Mancc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachincc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emailncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sdtncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngayncc")
                        .HasColumnType("TEXT");

                    b.HasKey("Mancc");

                    b.ToTable("Nhacungcap");
                });
#pragma warning restore 612, 618
        }
    }
}
