// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace btlnhom32.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20221129221739_Xuathang")]
    partial class Xuathang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("btl_nhom32.Models.Chucvucv", b =>
                {
                    b.Property<string>("Idcv")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motacn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tencv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Idcv");

                    b.ToTable("Chucvucv");
                });

            modelBuilder.Entity("btl_nhom32.Models.Hanghoa", b =>
                {
                    b.Property<string>("Mahh")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dvtinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenhh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("gbhh")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("gvhh")
                        .HasColumnType("TEXT");

                    b.HasKey("Mahh");

                    b.HasIndex("Tenth");

                    b.ToTable("Hanghoa");
                });

            modelBuilder.Entity("btl_nhom32.Models.Khachhang", b =>
                {
                    b.Property<string>("Makh")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachikh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sdtkh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenkh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Makh");

                    b.ToTable("Khachhang");
                });

            modelBuilder.Entity("btl_nhom32.Models.Kho", b =>
                {
                    b.Property<string>("Makho")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dckho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Makho");

                    b.ToTable("Kho");
                });

            modelBuilder.Entity("btl_nhom32.Models.Kiemkho", b =>
                {
                    b.Property<string>("Idkk")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mahh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Makho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Ngaykk")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sluongkk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Idkk");

                    b.HasIndex("Mahh");

                    b.HasIndex("Makho");

                    b.ToTable("Kiemkho");
                });

            modelBuilder.Entity("btl_nhom32.Models.Nhacungcap", b =>
                {
                    b.Property<string>("Mancc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachincc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emailncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sdtncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngayncc")
                        .HasColumnType("TEXT");

                    b.HasKey("Mancc");

                    b.ToTable("Nhacungcap");
                });

            modelBuilder.Entity("btl_nhom32.Models.Nhanvien", b =>
                {
                    b.Property<string>("Manv")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachinv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emailnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gioitinhnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sdtnv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tencv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tennv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngaylamnv")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngaynv")
                        .HasColumnType("TEXT");

                    b.HasKey("Manv");

                    b.HasIndex("Tencv");

                    b.ToTable("Nhanvien");
                });

            modelBuilder.Entity("btl_nhom32.Models.Nhaphang", b =>
                {
                    b.Property<string>("Idnh")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mahh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Makho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mancc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soluongnh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngaynh")
                        .HasColumnType("TEXT");

                    b.HasKey("Idnh");

                    b.HasIndex("Mahh");

                    b.HasIndex("Makho");

                    b.HasIndex("Mancc");

                    b.ToTable("Nhaphang");
                });

            modelBuilder.Entity("btl_nhom32.Models.Thuonghieu", b =>
                {
                    b.Property<string>("Idth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Idth");

                    b.ToTable("Thuonghieu");
                });

            modelBuilder.Entity("btl_nhom32.Models.Xuathang", b =>
                {
                    b.Property<string>("Idxh")
                        .HasColumnType("TEXT");

                    b.Property<string>("Makh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngayxh")
                        .HasColumnType("TEXT");

                    b.Property<string>("trangtxh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Idxh");

                    b.HasIndex("Makh");

                    b.HasIndex("Manv");

                    b.ToTable("Xuathang");
                });

            modelBuilder.Entity("btl_nhom32.Models.Hanghoa", b =>
                {
                    b.HasOne("btl_nhom32.Models.Thuonghieu", "Thuonghieu")
                        .WithMany()
                        .HasForeignKey("Tenth")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thuonghieu");
                });

            modelBuilder.Entity("btl_nhom32.Models.Kiemkho", b =>
                {
                    b.HasOne("btl_nhom32.Models.Hanghoa", "Hanghoa")
                        .WithMany()
                        .HasForeignKey("Mahh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("btl_nhom32.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("Makho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hanghoa");

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("btl_nhom32.Models.Nhanvien", b =>
                {
                    b.HasOne("btl_nhom32.Models.Chucvucv", "Chucvucv")
                        .WithMany()
                        .HasForeignKey("Tencv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chucvucv");
                });

            modelBuilder.Entity("btl_nhom32.Models.Nhaphang", b =>
                {
                    b.HasOne("btl_nhom32.Models.Hanghoa", "Hanghoa")
                        .WithMany()
                        .HasForeignKey("Mahh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("btl_nhom32.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("Makho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("btl_nhom32.Models.Nhacungcap", "Nhacungcap")
                        .WithMany()
                        .HasForeignKey("Mancc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hanghoa");

                    b.Navigation("Kho");

                    b.Navigation("Nhacungcap");
                });

            modelBuilder.Entity("btl_nhom32.Models.Xuathang", b =>
                {
                    b.HasOne("btl_nhom32.Models.Khachhang", "Khachhang")
                        .WithMany()
                        .HasForeignKey("Makh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("btl_nhom32.Models.Nhanvien", "Nhanvien")
                        .WithMany()
                        .HasForeignKey("Manv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khachhang");

                    b.Navigation("Nhanvien");
                });
#pragma warning restore 612, 618
        }
    }
}
